---
- name: Create resourcegroup
  hosts: all
  tasks:
   - name: Create a Resource Group
      azure_rm_resourcegroup:
        name: test1
        location: centralindia
      register: rg
   - name: Display
     debug:
       var: rg
...
