#find public ip and input it as value to hosts
- name: Get Virtual Machine disk details Using Ansible
  hosts: "{{ansible_host}}"
  tasks:
  
   - name: Print the disk size only for sd disks
     debug:
      msg: "{{ ansible_facts.devices[item].size }}"
     loop: "{{ ansible_facts.devices.keys() | map('regex_search', 'sd.*') | select('string') | list }}"
