- name: Create a Virtual Machine on Azure Using Ansible
  hosts: localhost
  tasks:
   - name: Gather facts
     setup:
     register: apple
   - name: print
     debug:
      var: apple
   - name: Display Disk Information
     debug:
      var: ansible_facts.devices
   - name:
     debug:
      var: ansible_facts.devices.keys()
