#find public ip and input it as value to hosts
- name: Create a Virtual Machine on Azure Using Ansible
  hosts: 20.219.4.80
  tasks:
  
   - name: Print the disk size only for sd disks
     debug:
      msg: "{{ ansible_facts.devices[item].size }}"
     loop: "{{ ansible_facts.devices.keys() | map('regex_search', 'sd.*') | select('string') | list }}"
