
- name: Create a Virtual Machine on Azure Using Ansible
  hosts: localhost
  vars:
   resource_group: "test-ansible"
  tasks:
   - name: Get facts for all Public IPs within a resource groups
     azure_rm_publicipaddress_info:
      resource_group: "{{ resource_group }}"
     register: output_ip_address
    
   - name: print public ip
     debug:
      msg: "{{output_ip_address.publicipaddresses.msg.ip_address}}"
