
- name: Get Virtual Machine lvm details Using Ansible
  hosts: 20.219.4.80
  tasks:
  
   - name: Print Physical Volume
     command: /usr/sbin/pvs
     register: apple1
   - debug:
      var: apple1
   - name: Print Volume Group
     command: /usr/sbin/vgs
     register: apple2
   - debug:
      var: apple2
   - name: Print LogicalVolume
     command: /usr/sbin/lvs
     register: apple3
   - debug:
      var: apple3
