
- name: Get Virtual Machine disk details Using Ansible
  hosts: 20.219.4.80
  tasks:
  
   - name: Print Physical Volume
     command: pvs
     register: apple1
     debug:
      var: apple1
   - name: Print Volume Group
     command: vgs
     register: apple2
     debug:
      var: apple2
   - name: Print LogicalVolume
     command: lvs
     register: apple3
     debug:
      var: apple3
