---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get facts for all resource groups
      azure_rm_resourcegroup_info:
      register: group_array
    - debug:
        var: group_array
