---
- hosts: localhost
  tasks:
    - name: Get facts for all resource groups
      azure_rm_resourcegroup_info:
      register: rg
    - name: Print
      debug:
       #var: rg.resourcegroups
       msg: "{{ rg.resourcegroups.0.name }}"
       #msg: "{{ result.resourcegroups | selectattr('name') }}"
       #msg: "{{ rg.resourcegroups | selectattr('name')}}"
       #msg: "{{rg.resourcegroups | map(attribute='name')}}"
       #msg: "{{rg.resourcegroups}}"
       
       
