---
- hosts: localhost
  tasks:
    - name: Get facts for all resource groups
      azure_rm_resourcegroup_info:
      register: rg
    - name: Print
      debug: 
        msg: "{{ item | selectattr('name')}}"
      loop: "{{ rg.resourcegroups }}"
      
     # debug:
       #var: rg.resourcegroups
      # msg: "{{ rg.resourcegroups.0.name }}"
    #- debug: msg="{{ rg| map('match','name') | list }}"
       #msg: "{{ result.resourcegroups | selectattr('name') }}"
       #msg: "{{ rg.resourcegroups | selectattr('name')}}"
       #msg: "{{rg.resourcegroups | map(attribute='name')}}"
       #msg: "{{rg.resourcegroups}}"
       
       
