- name: Demo1
  hosts: localhost
  tasks:
    - name: Get facts for all virtual machines of a resource group
      azure_rm_virtualmachine_info:
        resource_group: "{{ resource_group }}"
      register: vm_info
    - debug:
         var: vm_info
