#This Playbook works on dynamic inventory created in controller.Need to choose dynamic inventory
- name: Get Virtual Machine disk details Using Ansible
  hosts: all
  tasks:
  
   - name: Print the disk size only for sd disks
     debug:
      msg: "{{ ansible_facts.devices[item].size }}"
     loop: "{{ ansible_facts.devices.keys() | map('regex_search', 'sd[c-d]+') | select('string') | list }}"
   
   - name: Print Physical Volume
     command: /usr/sbin/pvs
     register: apple1
   - debug:
      var: apple1.stdout_lines
   - name: Print Volume Group
     command: /usr/sbin/vgs
     register: apple2
   - debug:
      var: apple2.stdout_lines
   - name: Print LogicalVolume
     command: /usr/sbin/lvs
     register: apple3
   - debug:
      var: apple3.stdout_lines
